FROM centos/python-38-centos7

# Install system dependencies
USER 0
RUN sed -i.bak 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i.bak 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
    
RUN yum --disablerepo=centos-sclo-sclo install -y \
    python38 \
    python38-devel \
    zlib \
    zlib-devel \
    gcc \
    make \
    && yum clean all

# Set Python 3.8 as default
#RUN alternatives --set python3 /usr/bin/python3.8

WORKDIR /app

# Copy only requirements first to leverage Docker cache
COPY requirements.txt .

# Install dependencies directly with python
RUN pip install --no-cache-dir -r requirements.txt
#    /app/venv/bin/pip install --no-cache-dir "textual>=0.32.0,<0.33.0" && \
#    /app/venv/bin/python -m pip install --no-cache-dir "pyinstaller>=5.13.0,<6.0.0"

# Copy the rest of the application
COPY . .

# Build the binary using python -m
RUN python3 -m PyInstaller build.spec --clean

# Create artifacts directory with correct permissions
RUN mkdir -p /artifacts && \
    cp -r dist/* /artifacts/ && \
    chmod -R 777 /artifacts
